= Exchange 公開ポータルのカスタマイズ
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

Exchange 管理者または組織の所有者アクセス権がある場合、Exchange 公開ポータルの外観をカスタマイズできます。

公開ポータルにアクセスし、ナビゲーションバーの右にある [Customize (カスタマイズ)] をクリックします。

== ポータルデフォルト設定

ポータルのカスタマイズをデフォルト設定に戻す必要がある場合、次の値を使用します。

* 背景色: #262728
* テキストの色: #FFFFFF
* テキストの色 (有効): #00A2DF
* https://cdn.anypoint.mulesoft.com/artifacts/exchange-ui/images/hero-image-default.png[[Welcome (ようこそ)] セクションのヒーロー画像]
+
*注意:* ブラウザで画像を開き、右クリックして画像をコンピュータに保存します。Exchange で、画像をアップロードし、
ポータルの画像をコンピュータの画像に置き換えることができます。
+
* [Welcome (ようこそ)] セクションのテキストの色: #FFFFFF

== バナーテキスト

[Customize (カスタマイズ)] をクリックした後に、バナーテキストをクリックします。変更するテキストを削除し、
新しいテキストを追加します。

== 上部バーのカスタマイズ

上部ナビゲーションバーの外観を変更できます。

=== ロゴ画像

ロゴ画像ファイルを選択します。ファイル内の画像の高さが 60 ピクセルを超える場合、Exchange では画像が 60 ピクセルの高さにサイズ変更されます。画像は縦横比を保ったままサイズ変更されます。たとえば、500 x 500 ピクセルの画像は 60 x 60 ピクセルにサイズ変更されます。

画像ファイルには .svg、.png、.jpg、または .gif 形式を使用できます。

=== ブラウザタブのお気に入りアイコン

公開ポータルのブラウザタブに表示されるお気に入りアイコン画像を選択します。画像の最大サイズは、ブラウザの要件によって
異なります。お気に入りアイコンファイルには、最大 5 個のサイズ (16 x 16、32 x 32、64 x 64、128 x 128、512 x 512 など) を含めることができます。

=== 背景色

上部タスクバーの色に赤 - 緑 - 青 (RGB) の 16 進数値を選択します。

=== テキストの色

上部バーテキストに 16 進数の RGB 色を指定します。色は、白の #FFFFFF から黒の #000000 までの範囲です。少なくとも 3 つの 16 進文字を指定する必要があります。たとえば、#F42 を指定すると、#FF4422 の値が生成されます。この項目は大文字と小文字を区別しません。

=== 有効なテキストの色

テキストにマウスポインタが置かれているときの上部バーテキストの 16 進数の RGB 色を指定します。色は、白の #FFFFFF から黒の #000000 までの範囲です。少なくとも 3 つの 16 進文字を指定する必要があります。たとえば、#F42 を指定すると、#FF4422 の値が生成されます。この項目は大文字と小文字を区別しません。

== ヒーロー画像バナー

公開ポータルのバナーの画像を選択します。ヒーロー画像ファイルには .png、.jpg、または.gif 形式を使用できます。
バナー画像の最大ファイルサイズは 2 MB です。バナー画像をアニメーション GIF ファイルにすることもできます。

指定した画像は、ブラウザのウィンドウサイズによって決定されるウィンドウサイズに合わせて伸縮されます。高さは 220 ピクセルに固定されています。

=== バナーテキストの色

バナーテキストの 16 進数の赤 - 緑 - 青の色を指定します。色は、白の #FFFFFF から黒の #000000 までの範囲です。少なくとも 3 つの 16 進文字を指定する必要があります。たとえば、#F42 を指定すると、#FF4422 の値が生成されます。この項目は大文字と小文字を区別しません。

== カスタムページ

カスタムページは、公開ポータルの上部にタブとして表示されます。Exchange のビジュアルエディタまたはマークダウンエディタを使用して、テキスト、画像、または動画をページに追加します。

カスタムページを削除するには、[Delete Page (ページを削除)] をクリックします。このボタンが見つからない場合は、公開ポータルブラウザウィンドウのサイズを変更して [Delete Page (ページを削除)] ボタンを表示します。

== 関連情報

* xref:portal-vanity-domain.adoc[公開ポータルのバニティドメイン]
* xref:to-describe-an-asset.adoc[アセットの説明]
* https://stackoverflow.com/questions/4014823/does-a-favicon-have-to-be-32x32-or-16x16[Stack Overflow のお気に入りアイコンに関するディスカッション]
