= 公開ポータルへの API アセットの共有
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images/

. API アセットをクリックして詳細を表示します。
. [Share (共有)] をクリックして ​*[Add to the public portal (公開ポータルに追加)]*​ をクリックします。
. (省略可能) アセットを公開ポータルに置かずに前の [Share (共有)] メニューに戻る場合、
[Share Internally (内部で共有)] をクリックします。
. (省略可能) 続行する前に、[API Instances (API インスタンス)] をクリックしてインスタンスの表示設定を管理します。このリンクに従うと、
前の [Share (共有)] メニューに戻ります。
. 公開ポータルでパブリッシュするアセットのバージョンをクリックします。
. [Share (共有)] をクリックします[Share (共有)] をクリックしても何も起こらない場合は、ブラウザを更新して再度ログインし、アセットの共有を繰り返します。

公開ポータルは、インターネットでポータルの URL を使用するすべてのユーザに表示されます。公開ポータルの URL は ​`+https://anypoint.mulesoft.com/exchange/portals/ORGANIZATION_NAME/+`​ で始まります。公開ポータルからアセットを削除するには、次のセクションの説明に
従って、アセットを非公開にする必要があります。

== 公開ポータルからアセットを削除する

​*注意:*​ この手順は、ポータルからアセットを取り除くだけです。アセットは削除されません。

. Exchange でアセットをクリックして [Share (共有)] をクリックします。
. [Add to the Public Portal (公開ポータルに追加)] をクリックします。
. バージョンのチェックボックス項目をクリックしてオフにします。
. [Share (共有)] をクリックします
. Exchange でブラウザの画面を更新すると、アセットの [Overview (概要)] の
[Visibility (表示)] 設定が [Private (非公開)] に変更されています。

== 関連情報

* xref:about-portals.adoc[公開ポータル]
